trigger:
  batch: true
  branches:
    include:
    - main
    - master
    - develop
resources:
 repositories:
   - repository: template
     name: GEPIN_AS/pipeline-templates
     type: git
     ref: refs/heads/master
stages:
- stage: Build
  displayName: 'Executando Build'
  jobs:
  - template: templates/dotnet_framework_jobs.yml@template
    parameters:
      
      ## Project Key do projeto no SonarQube 
      ## Pipeline irá gerar automaticamente baseado no nome do repositório
      ## SonarQubeKey='SEFAZ:NOMEPROJETO:SCOPO' Ex.: SEFAZ:FDWEB:FRONTEND 
      # SonarProjectKey: $(SonarProjectKey)
      ## Project Name do projeto no SonarQube
      ## Pipeline irá gerar automaticamente baseado no nome do repositório
      ## Seguindo o padrão SonarQubeName='NOMEDOPROJETO.scopo' Ex.:FDWEB.backend  
      # SonarProjectName: $(SonarProjectName)
      ## Versão da análise do projeto no SonarQube 
      ## Por default, o pipeline irá usar o hash do commit usado na build
      ## Descomentar se quiser usar um valor específico
      # SonarProjectVersion: $(SonarProjectVersion)
      ## Sonar Exclusion dotnet framework
      ## Padrão aceito **/ClsCriptografia.cs,**/clsCriptografia.cs
      ## Separar por vírgula
      SonarExclusions: $(SonarExclusions)
      ## Caso a aplicação seja Windows Service Framework definir o valor EnabledTaskTransformation como true
      EnabledTaskTransformation: true
      ## AgentPool que será usado, por padrão será SEFAZ-DTI
      ## Outra opção será SEFAZ
      # AgentPool: $(AgentPool)